<!DOCTYPE html>
<html>
<head>
<title>Tue Nov 26, 2019 : #gfactory (osg)</title>
</head>
<body>
<h3>Tue Nov 26, 2019 : #gfactory (osg)</h3>
<span style="color: #e23f99"><span style="font-size: small">(09:47:35)</span> <b>marco.mascheroni:</b></span> <pre>11/22/19 16:36:35 (pid:109424) ******************************************************<br/>11/22/19 16:36:35 (pid:109424) ** condor_starter (CONDOR_STARTER) STARTING UP<br/>11/22/19 16:36:35 (pid:109424) ** /var/lib/condor/execute/dir_84137/glide_PfPRVq/main/condor/sbin/condor_starter<br/>11/22/19 16:36:35 (pid:109424) ** SubsystemInfo: name=STARTER type=STARTER(8) class=DAEMON(1)<br/>11/22/19 16:36:35 (pid:109424) ** Configuration: subsystem:STARTER local:&lt;NONE&gt; class:DAEMON<br/>11/22/19 16:36:35 (pid:109424) ** $CondorVersion: 8.8.2 Apr 11 2019 BuildID: 465890 $<br/>11/22/19 16:36:35 (pid:109424) ** $CondorPlatform: x86_64_RedHat6 $<br/>11/22/19 16:36:35 (pid:109424) ** PID = 109424<br/>11/22/19 16:36:35 (pid:109424) ** Log last touched 11/22 16:36:19<br/>11/22/19 16:36:35 (pid:109424) ******************************************************<br/>11/22/19 16:36:35 (pid:109424) Using config source: /var/lib/condor/execute/dir_84137/glide_PfPRVq/condor_config<br/>11/22/19 16:36:35 (pid:109424) config Macros = 387, Sorted = 387, StringBytes = 27208, TablesBytes = 13972<br/>11/22/19 16:36:35 (pid:109424) CLASSAD_CACHING is OFF<br/>11/22/19 16:36:35 (pid:109424) Daemon Log is logging: D_ALWAYS D_ERROR<br/>11/22/19 16:36:35 (pid:109424) Daemoncore: Listening at &lt;0.0.0.0:33763&gt; on TCP (ReliSock).<br/>11/22/19 16:36:35 (pid:109424) DaemonCore: command socket at &lt;10.5.242.35:33763?addrs=10.5.242.35-33763&amp;noUDP&gt;<br/>11/22/19 16:36:35 (pid:109424) DaemonCore: private command socket at &lt;10.5.242.35:33763?addrs=10.5.242.35-33763&gt;<br/>11/22/19 16:36:35 (pid:109424) CCBListener: registered with CCB server <a href="http://flock.opensciencegrid.org:9821">flock.opensciencegrid.org:9821</a> as ccbid 192.170.227.251:9821?addrs=192.170.227.251-9821&amp;alias=flock.openscienceg<br/><a href="http://rid.org#242550">rid.org#242550</a><br/>11/22/19 16:36:35 (pid:109424) Communicating with shadow &lt;129.57.199.132:9615?addrs=129.57.199.132-9615&amp;noUDP&amp;sock=11714_5295_206346&gt;<br/>11/22/19 16:36:35 (pid:109424) Submitting machine is "<a href="http://scosg16.jlab.org">scosg16.jlab.org</a>"<br/>11/22/19 16:36:36 (pid:109424) setting the orig job name in starter<br/>11/22/19 16:36:36 (pid:109424) setting the orig job iwd in starter<br/>11/22/19 16:36:36 (pid:109424) Chirp config summary: IO false, Updates false, Delayed updates true.<br/>11/22/19 16:36:36 (pid:109424) Initialized IO Proxy.<br/>11/22/19 16:36:36 (pid:109424) Done setting resource limits<br/>11/22/19 16:36:36 (pid:109424) FILETRANSFER: "/var/lib/condor/execute/dir_84137/glide_PfPRVq/main/condor/libexec/curl_plugin -classad" did not produce any output, ignoring<br/>11/22/19 16:36:36 (pid:109424) FILETRANSFER: failed to add plugin "/var/lib/condor/execute/dir_84137/glide_PfPRVq/main/condor/libexec/curl_plugin" because: FILETRANSFER:1:"/var/lib/co<br/>ndor/execute/dir_84137/glide_PfPRVq/main/condor/libexec/curl_plugin -classad" did not produce any output, ignoring<br/>11/22/19 16:39:41 (pid:109770) condor_read(): timeout reading 65536 bytes from daemon at &lt;129.57.199.132:9615&gt;.<br/>11/22/19 16:39:41 (pid:109770) ReliSock::get_bytes_nobuffer: Failed to receive file.<br/>11/22/19 16:39:41 (pid:109770) get_file(): ERROR: received 484704256 bytes, expected 5546558453!<br/>11/22/19 16:39:41 (pid:109770) DoDownload: STARTER at 10.5.242.35 failed to receive file /var/lib/condor/execute/dir_84137/glide_PfPRVq/execute/dir_109424/run040881_random.hddm<br/>11/22/19 16:39:41 (pid:109424) File transfer failed (status=0).<br/>11/22/19 16:39:41 (pid:109424) ERROR "Failed to transfer files" at line 2468 in file /slots/01/dir_1753876/sources/src/condor_starter.V6.1/jic_shadow.cpp<br/>11/22/19 16:39:41 (pid:109424) ShutdownFast all jobs.<br/>11/22/19 16:40:02 (pid:109424) condor_read() failed: recv(fd=13) returned -1, errno = 104 Connection reset by peer, reading 21 bytes from &lt;129.57.199.132:9615&gt;.<br/>11/22/19 16:40:02 (pid:109424) IO: Failed to read packet header<br/>11/22/19 16:40:02 (pid:109424) Lost connection to shadow, waiting 2400 secs for reconnect</pre><br/><br/>
<span style="color: #e23f99"><span style="font-size: small">(09:47:52)</span> <b>marco.mascheroni:</b></span> I found the starter log related to the message above @rynge<br/>
<span style="color: #e23f99"><span style="font-size: small">(09:48:55)</span> <b>marco.mascheroni:</b></span> This is the startd:<br/>
<span style="color: #e23f99"><span style="font-size: small">(09:48:59)</span> <b>marco.mascheroni:</b></span> <pre>11/22/19 16:36:35 (pid:99116) slot1: Changing activity: Idle -&gt; Busy<br/>11/22/19 16:36:36 (pid:99116) slot1[1466009.0]: Received job ClassAd update from starter :<br/>11/22/19 16:39:41 (pid:99116) slot1: Got ACTIVATE_CLAIM while in Claimed/Busy state, ignoring.<br/>11/22/19 16:39:41 (pid:99116) slot1: Called deactivate_claim()<br/>11/22/19 16:39:41 (pid:99116) slot1: State change: received RELEASE_CLAIM command<br/>11/22/19 16:39:41 (pid:99116) slot1: Changing state and activity: Claimed/Busy -&gt; Preempting/Vacating<br/>11/22/19 16:40:02 (pid:99116) slot1[1466009.0]: Received job ClassAd update from starter :<br/>11/22/19 16:40:02 (pid:99116) slot1[1466009.0]: Could not read update job ClassAd update from starter, assuming final_update<br/>11/22/19 16:40:02 (pid:99116) Starter pid 109424 exited with status 4<br/>11/22/19 16:40:02 (pid:99116) slot1: State change: starter exited<br/>11/22/19 16:40:02 (pid:99116) slot1: State change: No preempting claim, returning to owner<br/>11/22/19 16:40:02 (pid:99116) slot1: Changing state and activity: Preempting/Vacating -&gt; Owner/Idle<br/>11/22/19 16:40:02 (pid:99116) slot1: State change: IS_OWNER is false</pre><br/><br/>
<span style="color: #e23f99"><span style="font-size: small">(09:54:35)</span> <b>marco.mascheroni:</b></span> I think it is trying to downlad a 5.5Gb file called <tt>run040881_random.hddm</tt> from <tt><a href="http://scosg16.jlab.org">scosg16.jlab.org</a></tt> but getting a timeout after 400Mb. Is it a user accidentally ddos-ing a schedd?<br/>
<span style="color: #43761b"><span style="font-size: small">(09:56:01)</span> <b>blin:</b></span> @efajardo i forget, are you the contact for jlab users?<br/>
<span style="color: #a63024"><span style="font-size: small">(10:01:27)</span> <b>efajardo:</b></span> This should be @tbritton<br/>
<span style="color: #a63024"><span style="font-size: small">(10:01:42)</span> <b>efajardo:</b></span> @tbritton can you take a look :top:?<br/>
<span style="color: #4d5e26"><span style="font-size: small">(10:04:18)</span> <b>tbritton:</b></span> @marco.mascheroni is correct.  A debugging over-ride was accidentally left "in production". So yes scosg16 was getting ddos-ed from within.  This should be corrected (as of the evening 11/25)<br/>
<span style="color: #4d5e26"><span style="font-size: small">(10:05:56)</span> <b>tbritton:</b></span> Let me know if you are presently seeing this issue. And my apologies<br/>
</body>
</html>
