<!DOCTYPE html>
<html>
<head>
<title>Wed May 3, 2017 : #net-service (osg)</title>
</head>
<body>
<h3>Wed May 3, 2017 : #net-service (osg)</h3>
<span style="color: #4ec0d6"><span style="font-size: small">(07:27:12)</span> <b>smckee:</b></span> FYI, we have discovered some issues with the OSG network data flow.   Edgar found that some data is not able to be posted to ESmond on OSG.  He sees:<br/>
<span style="color: #4ec0d6"><span style="font-size: small">(07:28:20)</span> <b>smckee:</b></span> Looking at the django.log It looks something in postgresql is not really happy:<br/><br/>2017-05-02 15:04:35,842 [ERROR] /usr/lib/esmond/lib/python2.7/site-packages/django/core/handlers/base.py: Internal Server Error: /esmond/perfsonar/archive/731c4797f52d4fb7a55b470bbef46c46/<br/>Traceback (most recent call last):<br/>  File "/usr/lib/esmond/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response<br/>    response = wrapped_callback(request, *callback_args, **callback_kwargs)<br/>  File "/usr/lib/esmond/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view<br/>    return view_func(*args, **kwargs)<br/>  File "/usr/lib/esmond/lib/python2.7/site-packages/rest_framework/viewsets.py", line 85, in view<br/>    return self.dispatch(request, *args, **kwargs)<br/>  File "/usr/lib/esmond/lib/python2.7/site-packages/rest_framework/views.py", line 456, in dispatch<br/>    response = self.handle_exception(exc)<br/>  File "/usr/lib/esmond/lib/python2.7/site-packages/rest_framework/views.py", line 453, in dispatch<br/>    response = handler(request, *args, **kwargs)<br/>  File "/usr/lib/esmond/esmond/api/perfsonar/api_v2.py", line 902, in update<br/>    obj.save()<br/>  File "/usr/lib/esmond/esmond/api/perfsonar/api_v2.py", line 411, in save<br/>    rawsql_cursor.execute("UPDATE ps_event_types SET time_updated=now() WHERE event_type=%s AND metadata_id=(SELECT id FROM ps_metadata WHERE metadata_key=%s)", [self.event_type, self.metadata_key])<br/>  File "/usr/lib/esmond/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute<br/>    return self.cursor.execute(sql, params)<br/>  File "/usr/lib/esmond/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__<br/>    six.reraise(dj_exc_type, dj_exc_value, traceback)<br/>  File "/usr/lib/esmond/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute<br/>    return self.cursor.execute(sql, params)<br/>InternalError: invalid page in block 30831 of relation base/16384/16776<br/>
<span style="color: #4ec0d6"><span style="font-size: small">(07:28:35)</span> <b>smckee:</b></span> Looking at Postgresql logs I do see a problem:<br/>
<span style="color: #4ec0d6"><span style="font-size: small">(07:28:50)</span> <b>smckee:</b></span> ERROR:  invalid page in block 30893 of relation base/16384/16776<br/>ERROR:  invalid page in block 31053 of relation base/16384/16776<br/>ERROR:  invalid page in block 31253 of relation base/16384/16776<br/>ERROR:  invalid page in block 30831 of relation base/16384/16776<br/>ERROR:  invalid page in block 30893 of relation base/16384/16776<br/>ERROR:  invalid page in block 31053 of relation base/16384/16776<br/>ERROR:  invalid page in block 31253 of relation base/16384/16776<br/>ERROR:  invalid page in block 30831 of relation base/16384/16776<br/>ERROR:  invalid page in block 30893 of relation base/16384/16776<br/>ERROR:  invalid page in block 31053 of relation base/16384/16776<br/>
<span style="color: #4ec0d6"><span style="font-size: small">(07:29:09)</span> <b>smckee:</b></span> Following this thread to try to fix it:  <a href="https://www.postgresql.org/message-id/CA+RSxMhvDP7w_v80nXidCO2gMsN1wHv9vWx1wRtmX1Piv9MRqw@mail.gmail.com">https://www.postgresql.org/message-id/CA+RSxMhvDP7w_v80nXidCO2gMsN1wHv9vWx1wRtmX1Piv9MRqw@mail.gmail.com</a><br/>
<span style="color: #4ec0d6"><span style="font-size: small">(07:31:15)</span> <b>smckee:</b></span> esmond=# select count(*) from ps_event_types;<br/>ERROR:  MultiXactId 1371471872 has not been created yet -- apparent wraparound<br/>esmond=# select count(*) from ps_metadata;<br/> count<br/>--------<br/> 270077<br/>(1 row)<br/>
<span style="color: #4ec0d6"><span style="font-size: small">(07:31:29)</span> <b>smckee:</b></span> So another ERROR to track down.<br/>
<span style="color: #4ec0d6"><span style="font-size: small">(07:40:27)</span> <b>smckee:</b></span> Found this thread...this may be hard to fix: <a href="https://dba.stackexchange.com/questions/143516/postgres-multixactid-error">https://dba.stackexchange.com/questions/143516/postgres-multixactid-error</a><br/>
</body>
</html>
