<!DOCTYPE html>
<html>
<head>
<title>Sun Jul 16, 2017 : #software (osg)</title>
</head>
<body>
<h3>Sun Jul 16, 2017 : #software (osg)</h3>
<span style="color: #965d1b"><span style="font-size: small">(17:27:16)</span> <b>briedel:</b></span> <b>@channel</b> gfal in the osg cvmfs in version 3.3.26 and 3.4.1 is broken<br/>for plain <tt>gfal-ls</tt> errors out<br/><pre><br/>[briedel@midway-login1 ~]$ gfal-ls <a href="gsiftp://ccdcacli235.in2p3.fr:2811/pnfs/in2p3.fr/data/xenon.biggrid.nl/rucio/x1t_SR001_170716_0455_tpc/1e/45/XENON1T-11299-000020000-000020550-000000551.zip">gsiftp://ccdcacli235.in2p3.fr:2811/pnfs/in2p3.fr/data/xenon.biggrid.nl/rucio/x1t_SR001_170716_0455_tpc/1e/45/XENON1T-11299-000020000-000020550-000000551.zip</a><br/>Traceback (most recent call last):<br/>  File "/cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.4/3.4.1/el6-x86_64/usr/bin/gfal-ls", line 24, in &lt;module&gt;<br/>    from gfal2_util.shell import Gfal2Shell<br/>  File "/cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.4/3.4.1/el6-x86_64/usr/lib/python2.6/site-packages/gfal2_util/shell.py", line 23, in &lt;module&gt;<br/>    from base import CommandBase<br/>  File "/cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.4/3.4.1/el6-x86_64/usr/lib/python2.6/site-packages/gfal2_util/base.py", line 32, in &lt;module&gt;<br/>    import gfal2<br/>ImportError: libjson-c.so.2: cannot open shared object file: No such file or directory<br/></pre><br/>same error when running inside python<br/><pre><br/>[briedel@midway-login1 ~]$ python -c "import gfal2"<br/>Traceback (most recent call last):<br/>  File "&lt;string&gt;", line 1, in &lt;module&gt;<br/>ImportError: libjson-c.so.2: cannot open shared object file: No such file or directory<br/></pre><br/>
</body>
</html>
