<!DOCTYPE html>
<html>
<head>
<title>Fri Nov 16, 2018 : #xcache (osg)</title>
</head>
<body>
<h3>Fri Nov 16, 2018 : #xcache (osg)</h3>
<span style="color: #c386df"><span style="font-size: small">(15:06:40)</span> <b>matyas:</b></span> having trouble with reporting from stashcache<br/><pre>Nov 16 14:51:18 <a href="http://sc-cache.chtc.wisc.edu">sc-cache.chtc.wisc.edu</a> stashcache[375684]: Traceback (most recent call last):<br/>Nov 16 14:51:18 <a href="http://sc-cache.chtc.wisc.edu">sc-cache.chtc.wisc.edu</a> stashcache[375684]: File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap<br/>Nov 16 14:51:18 <a href="http://sc-cache.chtc.wisc.edu">sc-cache.chtc.wisc.edu</a> stashcache[375684]: self.run()<br/>Nov 16 14:51:18 <a href="http://sc-cache.chtc.wisc.edu">sc-cache.chtc.wisc.edu</a> stashcache[375684]: File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run<br/>Nov 16 14:51:18 <a href="http://sc-cache.chtc.wisc.edu">sc-cache.chtc.wisc.edu</a> stashcache[375684]: self._target(*self._args, **self._kwargs)<br/>Nov 16 14:51:18 <a href="http://sc-cache.chtc.wisc.edu">sc-cache.chtc.wisc.edu</a> stashcache[375684]: File "/usr/sbin/stashcache", line 97, in stat_collector<br/>Nov 16 14:51:18 <a href="http://sc-cache.chtc.wisc.edu">sc-cache.chtc.wisc.edu</a> stashcache[375684]: self.advertise_cache_stats()<br/>Nov 16 14:51:18 <a href="http://sc-cache.chtc.wisc.edu">sc-cache.chtc.wisc.edu</a> stashcache[375684]: File "/usr/sbin/stashcache", line 140, in advertise_cache_stats<br/>Nov 16 14:51:18 <a href="http://sc-cache.chtc.wisc.edu">sc-cache.chtc.wisc.edu</a> stashcache[375684]: coll.advertise([cache_ad], 'UPDATE_STARTD_AD')<br/>Nov 16 14:51:18 <a href="http://sc-cache.chtc.wisc.edu">sc-cache.chtc.wisc.edu</a> stashcache[375684]: ValueError: Failed to advertise to collector</pre><br/>
<span style="color: #53b759"><span style="font-size: small">(15:14:50)</span> <b>marian:</b></span> maybe @jthiltges has clue?<br/>
<span style="color: #53b759"><span style="font-size: small">(15:15:18)</span> <b>marian:</b></span> you’re using latest /usr/sbin/stashcache from 0.10 release, @matyas?<br/>
<span style="color: #c386df"><span style="font-size: small">(15:16:05)</span> <b>matyas:</b></span> stashcache-daemon-0.10-1.osg34.el7.noarch<br/>
<span style="color: #53b759"><span style="font-size: small">(15:22:56)</span> <b>marian:</b></span> I’d file github issue?<br/>
<span style="color: #53b759"><span style="font-size: small">(15:23:14)</span> <b>marian:</b></span> and we take it from there? or SOFTWARE one…<br/>
<span style="color: #c386df"><span style="font-size: small">(15:25:41)</span> <b>matyas:</b></span> I don't really have enough information yet... any ideas about how to debug?<br/>
<span style="color: #e06b56"><span style="font-size: small">(15:52:13)</span> <b>jthiltges:</b></span> Hrm. That error is being thrown by the python htcondor module. Can the server reach <a href="http://collector1.opensciencegrid.org:9619">collector1.opensciencegrid.org:9619</a> and/or <a href="http://collector2.opensciencegrid.org:9619">collector2.opensciencegrid.org:9619</a> ?<br/>
<span style="color: #c386df"><span style="font-size: small">(16:00:42)</span> <b>matyas:</b></span> <pre>$ condor_status -pool <a href="http://collector2.opensciencegrid.org:9619">collector2.opensciencegrid.org:9619</a>  <br/>Name                                   OpSys      Arch   State     Activity L<br/><br/><a href="mailto:xrootd@ceph-gridftp1.grid.uchicago.edu">xrootd@ceph-gridftp1.grid.uchicago.edu</a> undefined  undefined undefined undefin<br/><a href="mailto:xrootd@fiona-r-uva.vlan7.uvalight.net">xrootd@fiona-r-uva.vlan7.uvalight.net</a>  undefined  undefined undefined undefin<br/><a href="mailto:xrootd@osg-gftp.pace.gatech.edu">xrootd@osg-gftp.pace.gatech.edu</a>        undefined  undefined undefined undefin<br/><a href="mailto:xrootd@stash.farm.particle.cz">xrootd@stash.farm.particle.cz</a>          undefined  undefined undefined undefin<br/><a href="mailto:xrootd@xcache-11.t2.ucsd.edu">xrootd@xcache-11.t2.ucsd.edu</a>           undefined  undefined undefined undefin<br/><br/>                     Machines Owner Claimed Unclaimed Matched Preempting  Drain<br/><br/>               Total        0     0       0         0       0          0      0<br/><br/>                    (Omitted 5 malformed ads in computed attribute totals)</pre><br/>
<span style="color: #c386df"><span style="font-size: small">(16:02:03)</span> <b>matyas:</b></span> similar for collector1<br/>
<span style="color: #e06b56"><span style="font-size: small">(16:02:04)</span> <b>jthiltges:</b></span> Should probably catch the error, rather than dying. <a href="https://github.com/opensciencegrid/StashCache-Daemon/pull/18">https://github.com/opensciencegrid/StashCache-Daemon/pull/18</a><br/>
<span style="color: #c386df"><span style="font-size: small">(16:03:01)</span> <b>matyas:</b></span> why ValueError ... gotta complain to @bbockelm or someone about that one<br/>
<span style="color: #e06b56"><span style="font-size: small">(16:03:06)</span> <b>jthiltges:</b></span> I'm seeing that on our stashcache as well.<br/>
<span style="color: #e06b56"><span style="font-size: small">(16:06:09)</span> <b>jthiltges:</b></span> putClassAd is returning 2?<br/><a href="https://github.com/htcondor/htcondor/blob/master/src/python-bindings/collector.cpp#L324">https://github.com/htcondor/htcondor/blob/master/src/python-bindings/collector.cpp#L324</a> ¯\_(ツ)_/¯<br/>
<span style="color: #e06b56"><span style="font-size: small">(16:08:01)</span> <b>jthiltges:</b></span> Started for us here:<br/><pre>Nov 16 09:13:34 <a href="http://hcc-stash.unl.edu">hcc-stash.unl.edu</a> stashcache: ValueError: Failed to advertise to collector</pre><br/>With a few instances on Oct 19, and one each on Nov 8 and Nov 9.<br/>
<span style="color: #c386df"><span style="font-size: small">(16:11:12)</span> <b>matyas:</b></span> I don't think my cache has ever managed to advertise<br/>
<span style="color: #43761b"><span style="font-size: small">(16:20:37)</span> <b>blin:</b></span> i am seeing this on my dev CE<br/><pre><br/>11/16/18 16:17:08 (D_ALWAYS) ERROR: SECMAN:2004:Failed to create security session to &lt;129.93.175.57:9619&gt; with TCP.|AUTHENTICATE:1003:Failed to authenticate with any method|AUTHENTICATE:1004:Failed to authenticate using GSI|GSI:5008:We are trying to connect to a daemon with certificate DN (/DC=org/DC=incommon/C=US/postalCode=53706/ST=WI/L=Madison/street=1210 West Dayton Street/O=University of Wisconsin-Madison/OU=OCIS/CN=<a href="http://collector2.opensciencegrid.org">collector2.opensciencegrid.org</a>), but the host name in the certificate does not match any DNS name associated with the host to which we are connecting (host name is '<a href="http://collector-itb.opensciencegrid.org">collector-itb.opensciencegrid.org</a>', IP is '129.93.175.57', Condor connection address is '&lt;129.93.175.57:9619?alias=collector-itb.opensciencegrid.org&gt;').  Check that DNS is correctly configured.  If the certificate is for a DNS alias, configure HOST_ALIAS in the daemon's configuration.  If you wish to use a daemon certificate that does not match the daemon's host name, make GSI_SKIP_HOST_CHECK_CERT_REGEX match the DN, or disable all host name checks by setting GSI_SKIP_HOST_CHECK=true or by defining GSI_DAEMON_NAME.<br/></pre><br/>
<span style="color: #43761b"><span style="font-size: small">(16:21:12)</span> <b>blin:</b></span> i'm going to guess we need to replace the collector host certs with ones from UNL<br/>
<span style="color: #e06b56"><span style="font-size: small">(16:27:22)</span> <b>jthiltges:</b></span> @blin If you access it as <tt><a href="http://collector2.opensciencegrid.org">collector2.opensciencegrid.org</a></tt> rather than <tt>collector-itb</tt>, do you get the same error?<br/>
<span style="color: #43761b"><span style="font-size: small">(16:37:00)</span> <b>blin:</b></span> yeah, i don't see any issues with that<br/>
</body>
</html>
